//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buscadores {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Buscadores.MyResource", typeof(MyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex by code.
        /// </summary>
        internal static string BuscarComplejosPorCódigoName {
            get {
                return ResourceManager.GetString("BuscarComplejosPorCódigoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities with null attribute .
        /// </summary>
        internal static string BuscarEntidadesConAtributoNuloName {
            get {
                return ResourceManager.GetString("BuscarEntidadesConAtributoNuloName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities with null attribute by field.
        /// </summary>
        internal static string BuscarEntidadesConAtributoNuloPorCampoName {
            get {
                return ResourceManager.GetString("BuscarEntidadesConAtributoNuloPorCampoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines with an odd number of vertex.
        /// </summary>
        internal static string BuscarLíneasConNúmeroImparDeVérticesName {
            get {
                return ResourceManager.GetString("BuscarLíneasConNúmeroImparDeVérticesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines crossing other lines.
        /// </summary>
        internal static string BuscarLineasCruzanConLineasName {
            get {
                return ResourceManager.GetString("BuscarLineasCruzanConLineasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All lines by criteria.
        /// </summary>
        internal static string BuscarLíneasPorCriterioName {
            get {
                return ResourceManager.GetString("BuscarLíneasPorCriterioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poligons by code.
        /// </summary>
        internal static string BuscarPolígonosPorCódigoName {
            get {
                return ResourceManager.GetString("BuscarPolígonosPorCódigoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points by code.
        /// </summary>
        internal static string BuscarPuntosPorCódigoName {
            get {
                return ResourceManager.GetString("BuscarPuntosPorCódigoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text by string.
        /// </summary>
        internal static string BuscarTextosPorCadenaName {
            get {
                return ResourceManager.GetString("BuscarTextosPorCadenaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text by code.
        /// </summary>
        internal static string BuscarTextosPorCódigoName {
            get {
                return ResourceManager.GetString("BuscarTextosPorCódigoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text by code and string.
        /// </summary>
        internal static string BuscarTextosPorCódigoYCadenaName {
            get {
                return ResourceManager.GetString("BuscarTextosPorCódigoYCadenaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All entities.
        /// </summary>
        internal static string BuscarTodasLasEntidadesName {
            get {
                return ResourceManager.GetString("BuscarTodasLasEntidadesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All entities by code.
        /// </summary>
        internal static string BuscarTodasLasEntidadesPorCodigoName {
            get {
                return ResourceManager.GetString("BuscarTodasLasEntidadesPorCodigoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All lines.
        /// </summary>
        internal static string BuscarTodasLasLíneasName {
            get {
                return ResourceManager.GetString("BuscarTodasLasLíneasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All complex.
        /// </summary>
        internal static string BuscarTodosLosComplejosName {
            get {
                return ResourceManager.GetString("BuscarTodosLosComplejosName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All polygons.
        /// </summary>
        internal static string BuscarTodosLosPolígonosName {
            get {
                return ResourceManager.GetString("BuscarTodosLosPolígonosName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All points.
        /// </summary>
        internal static string BuscarTodosLosPuntosName {
            get {
                return ResourceManager.GetString("BuscarTodosLosPuntosName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All texts.
        /// </summary>
        internal static string BuscarTodosLosTextosName {
            get {
                return ResourceManager.GetString("BuscarTodosLosTextosName", resourceCulture);
            }
        }
    }
}
